FROM joshwyant/gcc-cross as compiler
WORKDIR /src
COPY . .
RUN chmod 777 build && ./build

FROM joshwyant/vdisk-tools as packager
WORKDIR /src
COPY --from=compiler /src/bin ./bin
COPY package .
RUN chmod 777 package && ./package

FROM ubuntu as emulator
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install qemu-system-i386 -y

FROM emulator as runner
WORKDIR /src
COPY --from=packager /src/hdd.img .
